In [2]:
import numpy as np

### Converting list into Array

In [3]:
ar1=np.array([1,2,3])
ar2=np.array([[1,2,3],[12,13,14]])

In [5]:
print("ar1:",ar1)
print("ar2:",ar2)

ar1: [1 2 3]
ar2: [[ 1  2  3]
 [12 13 14]]


### List vs Numpy

In [9]:
list1=[1,0,0]
list1*4

[1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0]

In [10]:
ar1*3

array([3, 6, 9])

In [11]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((7,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.full((4,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [19]:

np.random.random((3,4))

array([[0.37376419, 0.54906475, 0.56565896, 0.45766677],
       [0.33524546, 0.7569546 , 0.42281406, 0.37108672],
       [0.03562672, 0.57570929, 0.52895902, 0.90589987]])

In [20]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
print(ar2.shape)
print(ar2.size)
print(ar2.ndim)
print(ar2.dtype)



(2, 3)
6
2
int64


In [27]:
ar3=np.arange(20)
ar4=ar3.reshape((4,5))

In [29]:
ar4.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [30]:
ar4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
ar5=ar4.ravel()

In [35]:
ar5[0]=100

In [36]:
ar4

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

In [37]:
ar4.T

array([[100,   5,  10,  15],
       [  1,   6,  11,  16],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [  4,   9,  14,  19]])