In [3]:
import numpy as np

In [7]:
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [8]:
a2d[2]

array([7, 8, 9])

In [11]:
a2d[2,1]

np.int64(8)

In [13]:
a2d[:,1]

array([2, 5, 8])

### Sorting

In [14]:
unsorted=np.array([1,5,3,2,9,6])

In [15]:
print(np.sort(unsorted))

[1 2 3 5 6 9]


In [19]:
unsorted2d=np.array([[1,5,3,2,9,6],[11,4,13,1,1,1]])

In [20]:
np.sort(unsorted2d,axis=0) #axis 0= coulmn wise sorting

array([[ 1,  4,  3,  1,  1,  1],
       [11,  5, 13,  2,  9,  6]])

In [21]:
np.sort(unsorted2d,axis=1) #axis 1= row wise sorting

array([[ 1,  2,  3,  5,  6,  9],
       [ 1,  1,  1,  4, 11, 13]])

# Filter

In [22]:
num=np.array([1,2,3,4,5,6,7,8,9])

In [24]:
even=num[num%2==0]

In [25]:
even

array([2, 4, 6, 8])

# Filter with mask

In [26]:
mask=num>5  # mask is  basically an expression

In [27]:
print(num[mask])

[6 7 8 9]


# Fancy Indexing and where

In [28]:
ind=[1,8]
print(num[ind])

[2 9]


In [29]:
where_ind=np.where(num%3==0)  # where stire index of all the element in number which is is divisible by 3
print(num[where_ind]) # we are applying fancy indexing

[3 6 9]


In [31]:
condition_array=np.where(num>6,num*100,num*0)
print(condition_array)

[  0   0   0   0   0   0 700 800 900]


# Adding and removing element


In [34]:
a1=np.array([1,2,3,4,5])
a2=np.array([11,22,33,44,55])
print(a1+a2)

[12 24 36 48 60]


In [39]:
a3=np.concatenate((a1,a2,a1))

In [40]:
a3

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55,  1,  2,  3,  4,  5])

# array Compatibilty


In [42]:
a=np.array([1,2,3,4,5])
b=np.array([1,21,3,4,5,4])
a.shape==b.shape

False

# Adding row to a 2d aray


In [45]:
a3=np.array([[1,2,3],[4,5,6]])
a4=np.array([10,20,30]) #adding a row
a5=np.vstack((a3,a4))
a5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [50]:
a6=np.array([[0],[0],[0]]) # addind a coulmn
a7=np.hstack((a5,a6))

In [51]:
a7

array([[ 1,  2,  3,  0],
       [ 4,  5,  6,  0],
       [10, 20, 30,  0]])

# Deletion 

In [54]:
ax1=np.array([1,2,3,4,5,6,7])
deleted=np.delete(ax1,0)
deleted

array([2, 3, 4, 5, 6, 7])